"""The action definition for the UML3 toolbox."""
from enum import Enum

from gaphas.item import SE

from gaphor import UML, diagram
from gaphor import UML3, diagram
from gaphor.core import gettext
from gaphor.diagram.diagramtoolbox import ToolboxDefinition, ToolDef
from gaphor.diagram.diagramtools import PlacementTool
from gaphor.UML3 import diagramitems as uml3_items
from gaphor.UML3 import uml3
from gaphor.UML import diagramitems as uml_items
from gaphor.UML import diagramitems
from gaphor.UML.toolbox import (
    composite_association_config,
    history_pseudostate_config,
    initial_pseudostate_config,
    namespace_config,
    shared_association_config,
    metaclass_config
)

class FormalType(Enum):
    FORMAL = "formal"

# Actions: ((section (name, label, icon_name, shortcut)), ...)
uml3_toolbox_actions: ToolboxDefinition = (
    (
        gettext("General"),
        (
            ToolDef(
                "toolbox-pointer",
                gettext("Pointer"),
                "gaphor-pointer-symbolic",
                "Escape",
                item_factory=None,
            ),
            ToolDef(
                "toolbox-package",
                gettext("Package"),
                "gaphor-package-symbolic",
                "p",
                PlacementTool.new_item_factory(
                    diagramitems.PackageItem, UML.Package, config_func=namespace_config,
                ),
                handle_index=SE,
            ),
            ToolDef(
                "toolbox-comment",
                gettext("Comment"),
                "gaphor-comment-symbolic",
                "k",
                PlacementTool.new_item_factory(
                    diagram.general.CommentItem, UML.Comment
                ),
                handle_index=SE,
            ),
        ),
    ),
    (
        gettext("Sortals"),
        (
            ToolDef(
                "toolbox-kind",
                gettext("Kind"),
                "gaphor-sortal-kind-symbolic",
                "l",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypeKind,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
            ToolDef(
                "toolbox-subkind",
                gettext("Subkind"),
                "gaphor-sortal-subkind-symbolic",
                "a",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypeSubkind,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
            ToolDef(
                "toolbox-phase",
                gettext("Phase"),
                "gaphor-sortal-phase-symbolic",
                "p",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypePhase,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
            ToolDef(
                "toolbox-role",
                gettext("Role"),
                "gaphor-sortal-role-symbolic",
                "<Shift>R",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypeRole,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
            ToolDef(
                "toolbox-collective",
                gettext("Collective"),
                "gaphor-sortal-collective-symbolic",
                "c",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypeCollective,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
            ToolDef(
                "toolbox-quantity",
                gettext("Quantity"),
                "gaphor-sortal-quantity-symbolic",
                "q",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypeQuantity,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
            ToolDef(
                "toolbox-relator",
                gettext("Relator"),
                "gaphor-sortal-relator-symbolic",
                "t",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypeRelator,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
        ),
    ),
    (
        gettext("NonSortals"),
        (
            ToolDef(
                "toolbox-category",
                gettext("Category"),
                "gaphor-nonsortal-category-symbolic",
                "<Shift>C",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypeCategory,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
            ToolDef(
                "toolbox-phasemixin",
                gettext("Phasemixin"),
                "gaphor-nonsortal-phasemixin-symbolic",
                "o",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypePhasemixin,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
            ToolDef(
                "toolbox-mixin",
                gettext("Mixin"),
                "gaphor-nonsortal-mixin-symbolic",
                "ç",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypeMixin,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
            ToolDef(
                "toolbox-rolemixin",
                gettext("Rolemixin"),
                "gaphor-nonsortal-rolemixin-symbolic",
                "x",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypeRolemixin,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
        ),
    ),
    (
        gettext("Aspects"),
        (
            ToolDef(
                "toolbox-mode",
                gettext("Mode"),
                "gaphor-aspects-mode-symbolic",
                "r",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypeMode,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
            ToolDef(
                "toolbox-quality",
                gettext("Quality"),
                "gaphor-aspects-quality-symbolic",
                "<Shift>I",
                item_factory=PlacementTool.new_item_factory(
                    uml3_items.ClassItem,
                    UML3.StereotypeQuality,
                    config_func=namespace_config,
                ),
                handle_index=SE,
            ),
        ),
    ),
    (
        gettext("Relationship"),
        (
            ToolDef(
                "toolbox-associations-formal",
                gettext("Formal"),
                "gaphor-associations-formal-symbolic",
                "<Shift>F",
                item_factory=PlacementTool.new_item_factory(uml3_items.FormalItem),
            ),
            ToolDef(
                "toolbox-associations-material",
                gettext("Material"),
                "gaphor-associations-material-symbolic",
                "<Shift>B",
                item_factory=PlacementTool.new_item_factory(uml3_items.MaterialItem),
            ),
            ToolDef(
                "toolbox-associations-mediation",
                gettext("Mediation"),
                "gaphor-associations-mediation-symbolic",
                "<Shift>A",
                item_factory=PlacementTool.new_item_factory(uml3_items.MediationItem),
            ),
            ToolDef(
                "toolbox-associations-characterization",
                gettext("Characterization"),
                "gaphor-associations-characterization-symbolic",
                "<Shift>E",
                item_factory=PlacementTool.new_item_factory(uml3_items.CharacterizationItem),
            ),
            ToolDef(
                "toolbox-associations-derivation",
                gettext("Derivation"),
                "gaphor-associations-derivation-symbolic",
                "d",
                item_factory=PlacementTool.new_item_factory(uml3_items.DerivationItem),
            ),
            ToolDef(
                "toolbox-associations-structuration",
                gettext("Structuration"),
                "gaphor-associations-structuration-symbolic",
                "s",
                item_factory=PlacementTool.new_item_factory(uml3_items.StructurationItem),
            ),
            ToolDef(
                "toolbox-agregations-partwhole",
                gettext("Partwhole"),
                "gaphor-agregations-partwhole-symbolic",
                "<Shift>P",
                item_factory=PlacementTool.new_item_factory(uml3_items.PartwholeItem),
            ),
            ToolDef(
                "toolbox-agregations-partwholeblack",
                gettext("Partwhole Black"),
                "gaphor-agregations-partwholeblack-symbolic",
                "<Shift>Ç",
                item_factory=PlacementTool.new_item_factory(uml3_items.PartwholeblackItem),
            ),
            ToolDef(
                "toolbox-agregations-componentof",
                gettext("Componentof"),
                "gaphor-agregations-componentof-symbolic",
                "m",
                item_factory=PlacementTool.new_item_factory(uml3_items.ComponentofItem),
            ),
            ToolDef(
                "toolbox-agregations-containment",
                gettext("Containment"),
                "gaphor-agregations-containment-symbolic",
                "n",
                item_factory=PlacementTool.new_item_factory(uml3_items.ContainmentItem),
            ),
            ToolDef(
                "toolbox-agregations-memberof",
                gettext("Memberof"),
                "gaphor-agregations-memberof-symbolic",
                "<Shift>M",
                item_factory=PlacementTool.new_item_factory(uml3_items.MemberofItem),
            ),
            ToolDef(
                "toolbox-agregations-memberofblack",
                gettext("Memberof Black"),
                "gaphor-agregations-memberofblack-symbolic",
                "<Shift>W",
                item_factory=PlacementTool.new_item_factory(uml3_items.MemberofblackItem),
            ),
            ToolDef(
                "toolbox-agregations-subcollectionof",
                gettext("Subcollectionof"),
                "gaphor-agregations-subcollectionof-symbolic",
                "<Shift>S",
                item_factory=PlacementTool.new_item_factory(uml3_items.SubcollectionofItem),
            ),
            ToolDef(
                "toolbox-agregations-subquantityof",
                gettext("Subquantityof"),
                "gaphor-agregations-subquantityof-symbolic",
                "<Shift>Q",
                item_factory=PlacementTool.new_item_factory(uml3_items.SubquantityofItem),
            ),
            ToolDef(
                "toolbox-dependency",
                gettext("Dependency"),
                "gaphor-dependency-symbolic",
                "<Shift>D",
                PlacementTool.new_item_factory(uml3_items.DependencywhiteItem),
            ),
            ToolDef(
                "toolbox-heritage",
                gettext("Heritage"),
                "gaphor-generalization-symbolic",
                "<Shift>G",
                item_factory = PlacementTool.new_item_factory(uml3_items.HeritageItem),
            ),
        ),
    ),
)
